development:
  adapter: mysql2
  database: titeres_dev
  username: root
  host: localhost

test:
  adapter: mysql2
  database: titeres_test
  username: root
  host: localhost

production:
  adapter: mysql2
  database: titeres_production
  username: root
  host: localhost